services:
  sus-postgres:
    image: postgres:latest
    container_name: sus-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sus
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sus

volumes:
  db-data:
